name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["Java CI with Gradle & Docker"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Debug Environment Variables
      run: |
        echo "EC2_USER=${{ secrets.EC2_USER }}"
        echo "EC2_HOST=${{ secrets.EC2_HOST }}"

    - name: Save EC2 Private Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
        chmod 600 ec2-key.pem
        ls -lah ec2-key.pem

    - name: SSH into EC2 & Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          echo "✅ EC2 접속 성공!"
          docker pull ${{ secrets.DOCKER_USERNAME }}/onclub-api:latest

          # ✅ 기존 컨테이너 중지 및 삭제
          docker stop onclub-api || true
          docker rm onclub-api || true

          # ✅ 새로운 컨테이너 실행
          docker run -d --name onclub-api -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/onclub-api:latest
        EOF
