name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["Java CI with Gradle & Docker"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: SSH into EC2 & Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST << EOF
          # ✅ Docker Hub 로그인
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # ✅ 기존 컨테이너 중지 및 삭제
          docker stop onclub-api || true
          docker rm onclub-api || true

          # ✅ 최신 Docker 이미지 가져오기
          docker pull ${{ secrets.DOCKER_USERNAME }}/onclub-api:latest

          # ✅ 새로운 컨테이너 실행
          docker run -d --name onclub-api -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/onclub-api:latest
        EOF
