name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["Java CI/CD with Gradle & Docker"]  # ✅ CI와 연동
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: SSH into EC2 & Deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > ec2-key.pem
        chmod 600 ec2-key.pem
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST << EOF
          sudo apt update
          sudo apt install -y docker-compose-plugin

          echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          docker pull ${{ secrets.DOCKER_USERNAME }}/onclub-api:latest

          docker-compose down || true

          docker-compose up -d
        EOF
