name: Java CI/CD with Gradle & Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    - name: Build with Gradle Wrapper
      env:
        OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
        OPEN_AI_API_URL: ${{ secrets.OPEN_AI_API_URL }}
        AWS_CREDENTIALS_ACCESS_KEY: ${{ secrets.AWS_CREDENTIALS_ACCESS_KEY }}
        AWS_CREDENTIALS_SECRET_KEY: ${{ secrets.AWS_CREDENTIALS_SECRET_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        DB_URL: ${{ secrets.DB_URL }}
        DB_NAME: ${{ secrets.DB_USER_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: ./gradlew build -x test

    - name: Log in to Docker Hub
      if: success()
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      if: success()
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/onclub-api:latest .

    - name: Push Docker Image
      if: success()
      run: docker push ${{ secrets.DOCKER_USERNAME }}/onclub-api:latest

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4.0.0
