name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./gradlew

    # 환경 변수 확인
    - name: Debug environment variables
      run: |
        echo "DB_URL=${{ secrets.DB_URL }}"
        echo "DB_USER_NAME=${{ secrets.DB_USER_NAME }}"
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
        echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}"
        echo "Checking application.yml contents:"
        cat src/main/resources/application.yml || echo "No application.yml found!"

    # application.yml 생성
    - name: Generate application.yml
      run: |
        cat <<EOF > src/main/resources/application.yml
        spring:
          datasource:
            url: "${{ secrets.DB_URL }}"
            username: "${{ secrets.DB_USER_NAME }}"
            password: "${{ secrets.DB_PASSWORD }}"
            driver-class-name: com.mysql.cj.jdbc.Driver
          jpa:
            database-platform: org.hibernate.dialect.MySQL8Dialect
            hibernate:
              ddl-auto: update
        EOF
      shell: bash

    # Gradle 빌드 실행 (환경 변수 강제 주입)
    - name: Build with Gradle Wrapper
      run: |
        DB_URL="${{ secrets.DB_URL }}" \
        DB_USER_NAME="${{ secrets.DB_USER_NAME }}" \
        DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
        ./gradlew build --info
